# Run during the 'gulp build' command
# Overrides these options in _config.yml

# Hides your drafts and future posts
future: false
show_drafts: false
# Gives you more accurate related posts
lsi: false
# Removes the upper limit for posts generated
limit_posts: 0
url: https://www.gizra.com

# Allow incremental rebuild
incremental: false

source: 'src'
destination: 'serve'

google:
  tracking_id: 'UA-6558346-3'
